<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>..\..\public.snk</AssemblyOriginatorKeyFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.CloudWatchLogs" />
    <PackageReference Include="AWSSDK.IdentityManagement" />
    <PackageReference Include="AWSSDK.Lambda" />
    <PackageReference Include="AWSSDK.S3" />
    <PackageReference Include="AWSSDK.SecurityToken" />
    <PackageReference Include="AWSSDK.SQS" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Logging" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\AWS.Messaging\AWS.Messaging.csproj" />
  </ItemGroup>

</Project>
