<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.CloudWatchLogs" />
    <PackageReference Include="AWSSDK.IdentityManagement" />
    <PackageReference Include="AWSSDK.Lambda" />
    <PackageReference Include="AWSSDK.S3" />
    <PackageReference Include="AWSSDK.SecurityToken" />
    <PackageReference Include="AWSSDK.SQS" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Logging" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\AWS.Messaging\AWS.Messaging.csproj" />
  </ItemGroup>

</Project>
