<Project Sdk="Microsoft.NET.Sdk.Web">
  
  <ItemGroup>
    <PackageReference Include="OpenTelemetry.Exporter.Console" />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" />
    <PackageReference Include="Swashbuckle.AspNetCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\AWS.Messaging.Telemetry.OpenTelemetry\AWS.Messaging.Telemetry.OpenTelemetry.csproj" />
    <ProjectReference Include="..\..\src\AWS.Messaging\AWS.Messaging.csproj" />
  </ItemGroup>

</Project>
