<Project Sdk="Microsoft.NET.Sdk">

  <Sdk Name="Aspire.AppHost.Sdk" Version="9.0.0" />

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsAspireHost>true</IsAspireHost>
    <UserSecretsId>979600ca-75aa-4eca-aff7-492ae2af1d88</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" />
    <PackageReference Include="Aspire.Hosting.AWS" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LambdaMessaging\LambdaMessaging.csproj" />
    <ProjectReference Include="..\PollyIntegration\PollyIntegration.csproj" />
    <ProjectReference Include="..\PublisherAPI\PublisherAPI.csproj" />
    <ProjectReference Include="..\SubscriberService\SubscriberService.csproj" />
  </ItemGroup>

</Project>
