<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>true</IsPackable>
    <Description>This package is a plugin for the AWS Message Processing Framework for .NET that allows a .NET Lambda function to handle messages that were published by the framework.</Description>
    <Product>AWS Message Processing Framework plugin for AWS Lambda</Product>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <Version>1.0.3</Version>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Amazon.Lambda.Core" />
    <PackageReference Include="Amazon.Lambda.SQSEvents" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AWS.Messaging\AWS.Messaging.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include=".\README.md" Pack="true" PackagePath="" />
  </ItemGroup>

</Project>
