name: Add Label to Dependabot PRs

on:
  pull_request:
    types:
      - opened

jobs:
  label-dependabot-pr:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    permissions:
      pull-requests: write

    steps:
      - name: Add Release Not Needed Label
        run: |
          gh pr edit ${{ github.event.pull_request.number }} --add-label "Release Not Needed"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
