name: Add Label to Dependabot PRs

on:
  pull_request:
    types:
      - opened

permissions: 
  id-token: write

jobs:
  label-dependabot-pr:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@8c3f20df09ac63af7b3ae3d7c91f105f857d8497 #v4
        with:
          role-to-assume: ${{ secrets.RELEASE_WORKFLOW_ACCESS_TOKEN_ROLE_ARN }}
          aws-region: us-west-2

      - name: Retrieve secret from AWS Secrets Manager
        uses: aws-actions/aws-secretsmanager-get-secrets@fbd65ea98e018858715f591f03b251f02b2316cb #v2.0.8
        with:
          secret-ids: |
            AWS_SECRET, ${{ secrets.RELEASE_WORKFLOW_ACCESS_TOKEN_NAME }}
          parse-json-secrets: true

      - name: Add Release Not Needed Label
        env:
          GITHUB_TOKEN: ${{ env.AWS_SECRET_TOKEN }}
        run: |
          gh pr edit ${{ github.event.pull_request.number }} --add-label "Release Not Needed"